site_name: Hangry Rail
docs_dir: src
site_dir: docs
site_description: 3D printed mounts and hangers for 1x4 and 2x4 rail setups.
site_url: https://sudo-robot-destroy.github.io/hangry_rail
repo_url: https://github.com/sudo-robot-destroy/hangry_rail

theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  features:
    - navigation.sidebar
    - navigation.top
    - search.suggest
    - search.highlight
