site_name: Hangry Rail
docs_dir: src
site_dir: docs
site_description: 3D printed mounts and hangers for garage tools.
site_url: https://sudo-robot-destroy.github.io/hangry_rail
repo_url: https://github.com/sudo-robot-destroy/hangry_rail

nav:
  - Information: index.md
  - GitHub: https://github.com/sudo-robot-destroy/hangry_rail
  - Onshape: https://cad.onshape.com/documents?nodeId=a861cdf0a7db1a27e0029c56&resourceType=folder

theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  features:
    - navigation.sidebar
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
